default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'catalogo_development' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'catalogo_test' %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>

# Action Cable (não precisa de banco)
cable:
  production:
    adapter: async

# SolidQueue (usa mesmo banco que a aplicação)
queue:
  production:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] %>
